FROM joezuntz/desc-pipe-test:1.0
MAINTAINER joezuntz@googlemail.com

#Enable root mode
USER root

#Install dependencies here
#RUN installation commands
#Commands that need the DM stack should be used in the form:
#RUN bash -lc "installation commands here"

# Must always end with these
USER vagrant
COPY run.sh /opt/desc/run.sh
